### ISSUE TITLE
Error in !is.na(server$DEBUG) && server$DEBUG

### ISSUE THREAD

**Issue by timyates** [rstudio/R-Websockets#3]
I have cloned the repository this morning to my machine, built it with `R CMD build R-Websockets/` and installed it with `R CMD INSTALL websockets_1.1.0.tar.gz`

When running any of the demo scripts, as soon as a client connects I get the error:

```
Error in !is.na(server$DEBUG) && server$DEBUG : 
  invalid 'y' type in 'x && y'
```

`traceback()` gives:

```
> traceback()
1: service(w)
```

And `sessionInfo()` returns:

```
> sessionInfo()
R version 2.13.1 (2011-07-08)
Platform: x86_64-apple-darwin9.8.0/x86_64 (64-bit)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/C/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] websockets_1.1.0 digest_0.5.1     caTools_1.12     bitops_1.0-4.1  
```

**Comment by bwlewis** [comment]
Hi Tim,

Jeff ryan and I are very actively updating the github repo. It's a big
rewrite to support the newer protocols that chrome just switched to.

Use websockets from cran for the stable branch.

-bryan
On Sep 22, 2011 5:36 AM, "Tim Yates" <
reply@reply.github.com>
wrote:

**Comment by timyates** [comment]
Ahhh, no worries :-) 

I thought I'd try and be _bleeding edge_ by using the latest master branch, but it seems I only ended up cutting myself ;-)

Maybe an extra branch for active development would help, and the master branch can be kept for the latest working code?

Good luck getting it all working though!

Really cool project :-)

**Comment by bwlewis** [comment]
Yes, you're right. I should have forked a dev branch.

But the good news is that the new package is way cooler. It will
support the older 00 protocol and the newer 04+ versions that google
chrome 14 just adopted. And we got rid of lots of dependencies
simplifying the package quite a bit.

The cookies stuff in the old package will go away (there will be
easier and more straightforward ways to associate data with clients).
That was part of Andy Green's underlying C library that we are no
longer using. Otherwise we're trying hard to maintain syntactic
compatability with the current stable version.

This will all be ready in about a week.

Best,

Bryan

On Thu, Sep 22, 2011 at 7:18 AM, Tim Yates
reply@reply.github.com
wrote:
